version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - net
  kafka-broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: broker
    container_name: broker
    depends_on:
    - zookeeper
    ports:
    - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - net
  msg:
    image: messenger
    container_name: msg
    environment:
      BROKER_HOST: 'broker:9092'
    networks:
      - net
  consumer:   
    image: receiver
    container_name: rcv
    depends_on:
      - msg
    networks:
      - net
  database:
    container_name: database
    image: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: temperatura
      MYSQL_USER: dockerdb
      MYSQL_PASSWORD: root
    volumes:
      - /home/marcin/db:/var/lib/mysql
    networks:
      - net

networks:
  net:
    ipam:
      config:
        - subnet: 172.30.0.0/24
 
